title: Maxwell Adeniji CEAMLS SAIRI Website Summer 2024 
logo: Professional_headshot.jpg
description: Hi! My name is Maxwell Adeniji and this is my CEAMLS SAIRI Website for Summer 2024.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
